baseURL = "https://thomas.lutkus.net/"
languageCode = "en-us"
title = "Thomas Lutkus"
theme = "PaperMod"

[params]
  author = "Thomas Lutkus"
  description = "Infrastructure engineering, Linux, Automation"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2